### ISSUE TITLE
'hugo' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by shadowempire123** [themesberg/flowbite-admin-dashboard#3]
```
PS D:\work\nodejs\flowbite-admin-dashboard-1.0.0> npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated core-js@3.19.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown 
up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 805 packages, and audited 806 packages in 17s

110 packages are looking for funding
  run `npm fund` for details        

12 vulnerabilities (1 moderate, 8 high, 3 critical)     

To address issues that do not require attention, run:   
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
PS D:\work\nodejs\flowbite-admin-dashboard-1.0.0> npm run start

> flowbite-admin-dashboard@1.0.0 start
> run-p start:dev:*


> flowbite-admin-dashboard@1.0.0 start:dev:webpack
> webpack --mode=development --watch


> flowbite-admin-dashboard@1.0.0 start:dev:hugo   
> hugo server -D --watch

'hugo' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "start:dev:hugo" exited with 1.
```

**Comment by shadowempire123** [comment]
ok, needs hugo.exe ...

**Comment by Rafiprabowo** [comment]
excuse me sir , where to
 download hugo.exe

**Comment by alonegamerdada** [comment]
> excuse me sir , where to download hugo.exe

same question here

**Comment by mshannaq** [comment]
The error message "sh: hugo: command not found" when running `npm run start` indicates that the `hugo` command is not recognized in your environment, which means Hugo is either not installed or not properly set up in your system's PATH. Hugo is a static site generator, and to resolve this issue, you'll need to install it.

Here are the steps to install Hugo:

### For macOS:
1. **Using Homebrew**:
   ```sh
   brew install hugo
   ```

### For Windows:
1. **Using Chocolatey**:
   Open a Command Prompt or PowerShell with administrator privileges and run:
   ```sh
   choco install hugo -confirm
   ```

or you can download it from https://gohugo.io/installation/

### For Linux:
1. **Using apt-get (Debian/Ubuntu)**:
   ```sh
   sudo apt-get update
   sudo apt-get install hugo
   ```

2. **Using Snap**:
   ```sh
   sudo snap install hugo --channel=extended
   ```

3. **Using Homebrew (if installed)**:
   ```sh
   brew install hugo
   ```

### Verify the Installation
After installation, verify that Hugo is installed correctly by running:
```sh
hugo version
```

### Add Hugo to PATH
If you installed Hugo manually or it's not in your PATH, you can add it by:

1. Finding the installation directory. For example, if you downloaded and extracted the Hugo binary to `/usr/local/bin`.
2. Adding the directory to your PATH:
   - **For macOS/Linux**: Edit your `~/.bashrc`, `~/.zshrc`, or `~/.profile` file to include:
     ```sh
     export PATH=$PATH:/usr/local/bin
     ```
   - **For Windows**:
     - Right-click on `This PC` and select `Properties`.
     - Click `Advanced system settings`.
     - Click the `Environment Variables` button.
     - Under `System variables`, find the `Path` variable, select it, and click `Edit`.
     - Click `New` and add the path to the directory where Hugo is installed.

After setting up Hugo, try running your command again:
```sh
npm run start
```

This should resolve the error, allowing Hugo to start correctly along with your other development tasks like `npm run start`
